# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - mongo # Ensures MongoDB starts before the server.

  # Adding MongoDB service as a database for the application
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017 # Exposes MongoDB's default port to the host
    volumes:
      - mongo_data:/data/db # Persists database data across container restarts
    restart: always # Restarts the container automatically in case of failure

# Define named volumes for persisting data between container restarts
volumes:
  mongo_data:
